# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  unit:
    strategy:
      matrix:
        go: ['1.20','1.21', '1.22']
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.os }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.os }}
          cache: false

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=coverage.txt ./...

      - name: Generate Coverage Report
        run: go tool cover -html=coverage.txt -o coverage.html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.html
